version: '3.7'

services:
  ## --------------------------------------------------
  ## | Web Server and application pm2 (node)
  ## --------------------------------------------------
  flight-app:
    container_name: flight-app
    build:
      context: ./
      dockerfile: .docker/app/Dockerfile
    ports:
      - "${APP_PORT}:${NODE_PORT}"
    restart: always
    depends_on:
      - flight-db
    env_file:
      - .env

  ## --------------------------------------------------
  ## | Database Server (Postgres)
  ## --------------------------------------------------
  flight-db:
    container_name: flight-db
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

